// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmwvxaddwgryijfckkcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptd3Z4YWRkd2dyeWlqZmNra2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTc3MDIsImV4cCI6MjA3MzY3MzcwMn0.9HCLXWN_SqC9JtKUnPtG4d6N6b8sID4Nnz-4VeNsnTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});